#!/bin/sh

ssh -tt ec2-user@18.218.133.65 <<EOF
    cd ~/Jenkins-test
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v10.11.0
    npm install
    npm install -g nodemon pm2
    pm2 restart app2.js
    exit
EOF